# Generated by Django 2.0 on 2019-03-21 22:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190317_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=15000),
        ),
    ]
